version: '3.4'

services:
    sqldata:
        image: ${DOCKER_REGISTRY-}rightmovedatabase
        build:
            context: .
            dockerfile: PostcodeProcessor/PostcodeProcessor.Console/Dockerfile.database.dockerfile
        #image: mcr.microsoft.com/mssql/server:2019-latest

    rabbitmq:
        image: rabbitmq:3-management

    postcodepopulator-console:
        image: ${DOCKER_REGISTRY-}postcodepopulator
        build:
            context: .
            dockerfile: PostcodePopulator/PostcodePopulator.Console/Dockerfile
        depends_on: 
            - rabbitmq

    postcodeprocessor-console:
        image: ${DOCKER_REGISTRY-}rightmovepostcodetolocationidmessageprocessor
        build:
            context: .
            dockerfile: PostcodeProcessor/PostcodeProcessor.Console/Dockerfile
        depends_on: 
            - rabbitmq
            - postcodepopulator-console
            - sqldata

    locationidprocessor-service:
        image: ${DOCKER_REGISTRY-}rightmovelocationidprocessorservice
        build:
            context: .
            dockerfile: LocationIdProcessor/LocationIdProcessor.Service/Dockerfile
        depends_on:
            - rabbitmq